### PR TITLE
Add support for using `h`, `s` as a JSX pragmas

### PR DESCRIPTION
**Pull request by wooorm**
This change tests that `hastscript` can be used as the pragma for JSX with bublé
and babel.

Code-wise, this adds support for using `h` to generate root nodes.
This is done by omitting the tag name (like so: `h()`, `h(null, 'child')`).
Previously, omitting a `name` resulted in the default element to be created
(`div` for `h`, `g` for `s`).

This change thus is a breaking change.
The old behavior is still available when passing an empty string: `h('')`.

Another aspect of supporting JSX is supporting fragments as children.
As fragments yield root nodes, we unravel them and use only their children.
While this could be seen a change, hast prohibits roots occurring in nodes,
so the unraveling instead fixes what would otherwise be a broken tree.

Related to: syntax-tree/xastscript#3.
Related to: syntax-tree/xastscript#4.

### CODE REVIEW

**Review by ChristianMurphy — APPROVED** [review]

**Comment by ChristianMurphy** [comment]
It looks like `null` can now be used as a element name, would the typings need to be updated to include `null`?

**Comment by wooorm** [comment]
Correct!

**Comment by remcohaszing** [comment]
It looks like the build was succesful, but Travis had some internal error. Can we rebase and release this? I don’t need this, but I do think it’s cool :smiley: 

I think the JSX type definitions can be literally copy-pasted from xastscript.

**Comment by wooorm** [comment]
I think it’s a major, so I was hoping to put that into the ESM rush™

**Pull request merged**
